### ISSUE TITLE
Add local storage to front-end

### ISSUE THREAD

**Issue by cskeogh** [JoshuaBuditama/slowvid#9]
Add local storage to the front-end. See @JakeBrown useState/useContext functionality from [pull 4](https://github.com/JoshuaBuditama/slowvid/pull/4)

**Comment by JakeBrown** [comment]
Commit d07783ec75690344e814cad66963dee3dbfe7e1f contains most of the boilerplate I suggest. We just need to adapt it to TypeScript if anyone is familiar with both React and TypeScript?

I'm familiar with React but have only used it with JavaScript... so it'll be a few days before I'm comfortable.

---
Some info on the design decision:

Localstorage is really the only way to store data client-side if we're running this in a browser. But again it's a simplification over native sdk's, so we'd need to document this decision the same way as we've chosen to use web technologies rather than native mobile.

Localstorage is really simple. See [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). It's as easy as:

```
localStorage.setItem('myCat', 'Tom');
const cat = localStorage.getItem('myCat');
```

All the other stuff in my commit (useContext and useState) are just there to make it play nicely with React. `useState` is kind of like an in-memory variable that allows React to dynamically re-render any components that use its value. 

`useContext` lets any component access the value without needing to explicitly pass it down as a prop.

**Comment by JakeBrown** [comment]
I've implemented this in TS. See here: https://github.com/JoshuaBuditama/slowvid/tree/wip/jb/local-storage.


Compiles with `"strict": false`, but need to add the TypeScript types before this can be considered complete. Someone please take this up and let me know if they need help!
